### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by AlmogBaku** [tawk/tawk-messenger-react#1]
Repo is not available at NPM at the moment

**Comment by jaoaustero** [comment]
Hello @AlmogBaku 

Yes the plugin is currently on development phase, sorry for not mentioning this plugin is not yet published.
This will be ready early next year.

**Comment by jaoaustero** [comment]
Hi @AlmogBaku 

We already released it as version 1.0.0, You can download it on npm
https://www.npmjs.com/package/@tawk.to/tawk-messenger-react
