### ISSUE TITLE
How Do I manually Open The Widget

### ISSUE THREAD

**Issue by DevYemi** [tawk/tawk-messenger-react#14]
Hi there, I'm trying to open the widget when ever the user clicks a separate button on my app and i have gone through the [https://github.com/tawk/tawk-messenger-vue-2/blob/424139a03b772dbd0e3463b9d551fcf49af7ffb6/docs/api-reference.md](url) but i can't find anything to solve my problem.

The only similar callback function i saw was the maximize(); function but that makes the widget take up the whole view port screen and that's not what i want. i just want to mimic the feature where the user clicks on the widget.

**Comment by jaoaustero** [comment]
Hello @DevYemi when you want to open the widget by other button, just call the maximize();

```js
const onClick = () => {
    tawkMessengerRef.current.maximize();
};
```

here is the [documentation](https://github.com/tawk/tawk-messenger-react/blob/main/docs/api-reference.md#maximize)

The design of the widget in mobile is taking up the whole screen, but in desktop it's like a popup on the corner. We don't have way to for users to resize/custom size of widget on mobile.

**Comment by DevYemi** [comment]
Thank you @jaoaustero
