### ISSUE TITLE
warning " > @tawk.to/tawk-messenger-react@2.0.1" has unmet peer dependency "react-scripts@^5.0.1".

### ISSUE THREAD

**Issue by younes-alouani** [tawk/tawk-messenger-react#16]
I'm getting this warning : 
warning " > @tawk.to/tawk-messenger-react@2.0.1" has unmet peer dependency "react-scripts@^5.0.1".

**Comment by jaoaustero** [comment]
This is resolve by this PR [#21](https://github.com/tawk/tawk-messenger-react/pull/21)
