### ISSUE TITLE
Minor documentation error

### ISSUE THREAD

**Issue by zehawki** [tawk/tawk-messenger-react#8]
Thank you for this component, works just fine.

Here in the doc: https://help.tawk.to/article/react-js :: How to use callbacks and expose functions

This

```
        <TawkMessengerReact
          propertyId="property_id"
          widgetId="default"
          useRef={tawkMessengerRef}
        />
```

should be

```
        <TawkMessengerReact
          propertyId="property_id"
          widgetId="default"
          ref={tawkMessengerRef}
        />
```

The prop should be `ref` not `useRef`.

**Comment by jaoaustero** [comment]
@zehawki Thank you, will update our content team

**Comment by jaoaustero** [comment]
@zehawki Documentation is updated, thank you very much.
