### ISSUE TITLE
open messenger programmatically

### ISSUE THREAD

**Issue by GautamChaudhary0923** [tawk/tawk-messenger-react#9]
how can i open this programmatically

**Comment by jaoaustero** [comment]
@GautamChaudhary0923 Hi, you can you can open the messenger automatically by following this [guide](https://github.com/tawk/tawk-messenger-react/blob/main/docs/api-reference.md#maximize)

**Comment by jaoaustero** [comment]
@GautamChaudhary0923 Hi, did you tried the solution? Just in case you have a question just mention me.
